# .golangci.yml
run:
  timeout: 2m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - errcheck
    - gosimple
    - typecheck
    - gocritic
    - revive
    - gci
    - depguard
    - nolintlint

issues:
  exclude-use-default: false

linters-settings:
  gci:
    skip-generated: true
  revive:
    ignore-generated-header: true
    severity: warning
